---
- name: remove docker RedHat
  yum:
    name: "{{ item.package }}"
    state: "{{ docker_package_state }}"
    update_cache: true
  with_items: "{{ docker_packages }}"

- name: Autoremove packages.
  yum:
    autoremove: yes
    state: "{{ docker_package_state }}"
