---
- name: Ensure dependencies are installed beforehand.
  yum: "name={{ docker_dependencies }} state=present"

- name: Add docker repository gpg key.
  rpm_key:
    key: "{{ docker_repo_yum_key }}"

- name: Copy docker repository.
  get_url:
    url: "{{ docker_repo_yum_url }}" 
    dest: /etc/yum.repos.d/docker.repo
    mode: '0644'

- name: Install/Remove Docker.
  yum:
    name: "{{ item.package }}-{{ item.version }}"
    allow_downgrade: yes
    state: "{{ docker_package_state }}"
    update_cache: true
  with_items: "{{ docker_packages }}"
  notify: docker service restart
