---
- name: Ensure dependencies are installed beforehand.
  apt: "name={{ docker_dependencies }} state=present"

- name: Add docker apt repository gpg key.
  apt_key:
    url: " {{ docker_repo_apt_key }}"

- name: Add docker apt repository.
  apt_repository:
    repo: "{{ docker_repo_apt_url }}"
    filename: 'docker'

- name: install docker debian
  apt:
    name: "{{ item.package }}={{ item.version }}"
    state: "{{ docker_package_state }}"
    force: true              # horrible esto. ver post 
    update_cache: true
  with_items: "{{ docker_packages }}"
  notify: docker service restart
