---

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: false
  changed_when: false

- name: add kubernetes yum repository
  copy:
    dest: "/etc/yum.repos.d/kubernetes.repo"
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl={{ k8s_repo_yum_url }}
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey={{ k8s_repo_yum_key }}
      #exclude=kubelet kubeadm kubectl

- name: Install kubernetes.
  yum:
    name: "{{ item.package }}-{{ item.version }}" 
    allow_downgrade: yes
    state: present
  with_items: "{{ k8s_packages }}"
