---

- name: Flush existing firewall rules.
  iptables:
    flush: true 
  changed_when: false

- name: Create br_netfilter file and add module.
  copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: 'br_netfilter'

- name: To see bridged traffic by iptables.
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
   
- name: Disable swap currently running.
  shell: "swapoff -a"
  args:
    executable: /bin/bash
  changed_when: false

- name: Disable swap
  replace: 
    path: "/etc/fstab"
    regexp: '^([^#].*?\sswap\s+(sw|swap)\s+.*)$'
    replace: '# \1'

- name: Change cgroup driver docker
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": { "max-size": "100m" },
        "storage-driver": "overlay2",
        "storage-opts": [ "overlay2.override_kernel_check=true" ]
      }
