---

- name: Check operating system.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Deploy control plane nodes.
  include_tasks: "master.yml"
  when: "'master01' in inventory_hostname"

- name: Add control plane nodes.
  include_tasks: "join-masters.yml"
  when: "'masters' in group_names and 'master01' not in inventory_hostname"

- name: Deploy worker nodes.
  include_tasks: "workers.yml"
  when: "'workers' in group_names"

- name: Undeploy nodes.
  include_tasks: "undeploy.yml"
  when: "k8s_undeploy is defined"
