---

- name: Check if already deployed node.
  shell: kubectl --kubeconfig=/etc/kubernetes/kubelet.conf cluster-info
  register: kubeadm_status
  changed_when: false

- name: Join Kubernetes cluster as worker node
  shell: "{{ hostvars['master01']['join_worker'] }}"
  when: kubeadm_status.failed == true
